on: [push, pull_request]
name: CI Behave
jobs:
  gitHubActionForPytest:
    name: GitHub Action for behave
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for behave
      with:
        args: behave
